Provide more information on the landing page
reposense/RepoSense pull request #1324
Opened 2020-09-07 05:03 UTC by dcshzj

Partially fixes #1205.

```
The report is not easy to understand for a first-time user, as
there is a lack of a quick introduction on the landing page.

Let's provide some basic information on some of the useful
functionality and provide a direct link to the relevant user guide.
```

2020-09-07 07:19 UTC, Tejas2805 commented
The issue kind of focuses on the fact that users will not want to go through the UG to understand how to read the report. But seems like a good start.

2020-09-07 07:29 UTC, dcshzj commented
Yep @Tejas2805, I identified 2 issues as both a first-time user and contributor which I tried to solve with this PR:

1. What are the features of RepoSense that I can take advantage of when I first reach this page?

I take for instance the link from CS2103 websites where it is labeled "iP Code Dashboard" which directs users to RepoSense, I'm not sure what to expect when I first arrive. Instead, I try to highlight the two main features of RepoSense that first-time users can take advantage of and from there, it introduces what RepoSense is about.

2. Where can I go to read more information on how to use RepoSense?

The current user guide is linked at the bottom of the page after all the repositories. Especially for a large student population, the user will have to "find" the correct link. Here, I direct them to the correct link in the user guide right when the user first enters the website.

2020-09-08 07:30 UTC, fzdy1914 commented
Sorry for the confusion in naming, but can you request the review from reposense/stage-1-active-reviewer instead of stage1 reviewer?

2020-09-08 07:33 UTC, Tejas2805 commented on frontend/src/static/js/main.js
> +    getReportUserGuideLink() {
Might be better to name it `getUsingReportLink()` I think.

2020-09-08 07:35 UTC, Tejas2805 commented on frontend/cypress/tests/codeView/codeView.js
> +      const expected = 'Welcome to RepoSense!The charts on the left shows the contribution activities, grouped by repository and author.To view the code attributed to a specific author, click the   
```suggestion
      const expected = 'Welcome to RepoSense!The charts on the left show the contribution activities, grouped by repository and author. To view the code attributed to a specific author, click the    icon next to that author\'s name. To view the breakdown of commits made by a specific author, click the    icon next to that author\'s name. To hide the code view and show only the activity charts, click the    icon on the left. Please see the  user guide  for more information on using the report.';
```

2020-09-08 07:36 UTC, Tejas2805 commented on frontend/src/index.pug
> +                      strong user guide
```suggestion
                      strong User Guide
```

2020-09-08 07:37 UTC, Tejas2805 requested changes
Have left a few comments.

2020-09-08 07:37 UTC, Tejas2805 commented on frontend/src/index.pug
> +                    | &nbsp; for more information on using the report.
```suggestion
                    | &nbsp; to get a better understanding of how to interpret the report.
```

2020-09-08 07:51 UTC, damithc commented
> @damithc Since it affects the UI though to a very small extent can get your review on this?

![image](https://user-images.githubusercontent.com/1673303/92447898-75d8b880-f1ea-11ea-98fd-6bd74a815abf.png)

Some comments/queries:
* This is not the RepoSense website. It's just a report generated by RepoSense. `Welcome to this RepoSense report`?
* `shows` -> `show`? Not sure.
* Are you using images for icons? If yes, shouldn't you use fontawesome instead?
* Last point: `... on the left` -> `... on the divider`?
* `Please see`: remove `Please`

2020-09-08 13:21 UTC, dcshzj commented
@damithc I incorporated some of the proposed changed. As for the icons, they are indeed using font awesome icons.

2020-09-08 13:34 UTC, damithc commented
> @damithc I incorporated some of the proposed changed. As for the icons, they are indeed using font awesome icons.

OK for me :-)

2020-09-13 15:16 UTC, jamessspanggg approved these changes
LGTM 👍🏻

2020-09-14 06:19 UTC, Tejas2805 approved these changes
LGTM!

2020-09-14 12:18 UTC, fzdy1914 approved these changes

2020-09-14 12:21 UTC, merged