[#1333] Fix loading of local reports
reposense/RepoSense pull request #1335
Opened 2020-09-29 16:31 UTC by Tejas2805

Fixes #1333 

```

```

2020-09-30 01:58 UTC, Tejas2805 commented
@jamessspanggg I think the problem should be fixed. Can try locally once.

2020-09-30 02:19 UTC, jamessspanggg requested changes

2020-09-30 02:19 UTC, jamessspanggg commented on frontend/src/static/js/main.js
> +        return `${window.BASE_URL}reposense/RepoSense`;
missing a `/` here

2020-09-30 03:06 UTC, jamessspanggg approved these changes

2020-10-01 04:33 UTC, fzdy1914 approved these changes

2020-10-03 07:28 UTC, merged