[#1375] Fix minor documentation inconsistencies in the User Guide and Developer Guide
reposense/RepoSense pull request #1376
Opened 2020-12-17 09:13 UTC by rolandyuwy

Fixes #1375 

Courtesy of @kkangs0226 for spotting these mistakes. 
I have taken time to find and fix additional typos and errors explained below:

Screenshots depict current bugs before fixing.
1) Standardize capitalization of instructions and explanations.
![image](https://user-images.githubusercontent.com/59356158/102466401-f2045700-4089-11eb-82f7-b6f733a27945.png)
![image](https://user-images.githubusercontent.com/59356158/102466680-4b6c8600-408a-11eb-9ff4-10b2427d43a2.png)

2) Fix formatting (bolding) issues.
![image](https://user-images.githubusercontent.com/59356158/102466468-08121780-408a-11eb-9a46-4ddf79d96778.png)

3) Correct typos.
![image](https://user-images.githubusercontent.com/59356158/102466537-1bbd7e00-408a-11eb-92a1-a781e38e3432.png)
![image](https://user-images.githubusercontent.com/59356158/102466578-27a94000-408a-11eb-882c-72a372364fe7.png)

4) Standardize hyperlinking of sections.
![image](https://user-images.githubusercontent.com/59356158/102466635-3bed3d00-408a-11eb-9e1d-5ca6d33f6c08.png)

Proposed commit message:

``` 
Current User Guide and Developer Guide contains several 
inconsistencies such as typos, grammatical errors and lack of 
standardization amongst sections.

Fixing these bugs will improve readability of these documentation.

Let's,
* standardize capitalization of instructions and explanations
* fix formatting issues
* correct typos
* standardize hyperlinking of sections

2020-12-17 23:18 UTC, Tejas2805 requested changes
Left some comments!

2020-12-17 23:18 UTC, Tejas2805 commented on docs/ug/generatingReports.md
> +**You can generate a RepoSense report remotely, without installing/running anything in your computer.** This is particularly useful when you are deciding whether to adopt RepoSense.
```suggestion
**You can generate a RepoSense report remotely without installing/running anything on your computer.** This is particularly useful when you are deciding whether to adopt RepoSense.
```

2020-12-17 23:18 UTC, Tejas2805 commented on docs/ug/cli.md
> +The sections below provide explanations for the flags.
```suggestion
The sections below provide explanations for each of the flags.
```

2020-12-18 13:55 UTC, rolandyuwy commented
> Left some comments!

Changes have been made, thank you!

2020-12-18 17:16 UTC, Tejas2805 reviewed
One last nit. Rest LGTM!

2020-12-18 17:16 UTC, Tejas2805 commented on docs/ug/cli.md
> +**`--formats LIST_OF_FORMATS`**: Specifies which file extensions to be included in the analysis
Missing "." at the end of sentence.

2020-12-19 08:12 UTC, rolandyuwy commented on docs/ug/cli.md
> +**`--formats LIST_OF_FORMATS`**: Specifies which file extensions to be included in the analysis
Thanks for the catch! Changes made.

2020-12-21 02:56 UTC, Tejas2805 approved these changes

2020-12-23 09:38 UTC, jamessspanggg commented
seems like there is another PR  #1379  that fixes the same thing, I think we should stick with one PR to fix these inconsistencies

2020-12-24 03:46 UTC, fzdy1914 commented
@rolandyuwy Do you agree that @kkangs0226 is the main contributor? If so, I will merge your changes to #1379 and also mention that you are a co-author.

2020-12-24 03:48 UTC, fzdy1914 commented
> @rolandyuwy Do you agree that @kkangs0226 is the main contributor? If so, I will merge your changes to #1379 and also mention that you are a co-author.

If so, please also provide your co-author detail like below:
```
Co-authored-by: Tejas Bhuwania <35946746+Tejas2805@users.noreply.github.com>
Co-authored-by: WANG CHAO <1229983126@qq.com>
```

2021-01-02 08:09 UTC, fzdy1914 commented
Close due to #1396

2021-01-02 08:09 UTC, closed without merging