[#795] Projectify frontend part
reposense/RepoSense pull request #1412
Opened 2021-01-18 10:55 UTC by gerhean

Working on this.

For preview: https://gerhean.github.io/tp-dashboard/

Things to fix: zoom tab does not reload on refresh because upgrading to vue 3 broke some stuff.

Possible Suggestions: store filtered repo in vuex.

Other things to look at: decouple stuff.

2021-01-19 10:02 UTC, fzdy1914 requested changes
PLS split it into two PRs. One is to upgrade it to Vue3, another is projectify it.

You may do the first task directly in `frontend`. So, we can verify that it will not break anything.

2021-01-19 10:18 UTC, gerhean commented
Is it not enough to just ensure that the new frontend is not broken? 

Vue3 completely breaks [vueify](https://github.com/vuejs/vueify) which the old frontend relies on. I'm not sure how to get around this.

One solution is to downgrade the new-frontend to Vue2, but feels redundant.

2021-01-19 13:13 UTC, fzdy1914 commented on new-frontend/src/components/v-summary-charts.vue
> +      this.$store.commit('updateTabZoomInfo', info);
This one should better be done in PR #1390. Do notice that, we are only changing related code with the topic of this PR. Pls only add necessary changes in this PR.

2021-03-22 13:25 UTC, gerhean commented
Downgraded to Vue 2.6.12

2021-03-22 16:36 UTC, fzdy1914 commented
> Downgraded to Vue 2.6.12

So you prefer to use Vue 2.6 first and then upgrade to Vue 3? Any other difficulty you face in using Vue3 in the current project not considering the issue for vueify?

2021-03-23 02:12 UTC, gerhean commented
> > Downgraded to Vue 2.6.12
> 
> So you prefer to use Vue 2.6 first and then upgrade to Vue 3? Any other difficulty you face in using Vue3 in the current project not considering the issue for vueify?

Some unexplainable errors which I find too hard to deal with.
![image](https://user-images.githubusercontent.com/16630400/112082408-4a368200-8bc0-11eb-9347-ec83c654896c.png)

2021-04-02 04:28 UTC, fzdy1914 commented
@gerhean Pls work on this PR sooner by my request. I want this PR to be merged by the end of this sem.

2021-04-02 04:50 UTC, gerhean commented
I think the only thing left is to ask @dcshzj how to set up the integration tests.

2021-04-02 04:58 UTC, dcshzj commented
You can modify build.gradle to point to the new frontend directory, assuming that it is a drop-in replacement. The report will then be generated using the new frontend and the cypress tests should be able to run automatically.

2021-04-05 07:23 UTC, fzdy1914 commented
Any more update? How is the deployment setup process going?

2021-04-06 11:29 UTC, gerhean commented
@fzdy1914 do i replace the old deployment with the new one, or set up another one.

2021-04-06 17:48 UTC, gerhean commented
Need #1527 to be reviewed and merged.

2021-06-25 03:52 UTC, damithc commented
@gerhean this PR contains a lot of work. Any chance of wrapping it up?

2021-06-25 04:32 UTC, gerhean commented
It is more or less done, I'll try to work on it tomorrow

2021-06-25 04:49 UTC, damithc commented
> It is more or less done, I'll try to work on it tomorrow

Great. thanks @gerhean 
Ping @fzdy1914 when ready

2021-06-27 03:26 UTC, fzdy1914 commented
Done

2021-06-27 03:26 UTC, fzdy1914 commented
Can go ahead. @gerhean

2021-06-29 02:45 UTC, gerhean commented
Should be mostly done, but not sure where to add documentation

2021-06-29 02:54 UTC, fzdy1914 commented
@gerhean Seems cannot find your new dashboard?

2021-06-29 02:58 UTC, gerhean commented
Example of  new dashboard is at gerhean#2

![image](https://user-images.githubusercontent.com/16630400/123730247-aba97380-d8c8-11eb-9466-e512e39a9c99.png)

Changes to github workflow files don't work until they are merged into master.

2021-06-29 03:02 UTC, fzdy1914 commented
@gerhean Yes, you are correct, forget this.

2021-06-30 13:17 UTC, fzdy1914 commented
@dcshzj Can you take a look at the gradlew/workflow part?

2021-06-30 13:18 UTC, fzdy1914 commented
The frontend part looks good to me.

2021-07-04 14:42 UTC, fzdy1914 commented
@dcshzj Re-Ping for review...

2021-07-04 14:50 UTC, dcshzj commented
Apologies for missing this. With the updates to our gradle workflow, we will be adding additional tasks for building using the new frontend. However, my understanding is that this pull request will replace the old frontend entirely. Will this be the case, or will we be deprecating the old frontend only in the future?

2021-07-05 13:18 UTC, fzdy1914 commented
> Apologies for missing this. With the updates to our gradle workflow, we will be adding additional tasks for building using the new frontend. However, my understanding is that this pull request will replace the old frontend entirely. Will this be the case, or will we be deprecating the old frontend only in the future?

That's a very good question. In the beginning, I want the two frontend to be in the repo at the same time. So, the refactoring process can be easier and not breaking the master branch in case anything happens. Meanwhile, I originally plan to merge it at the half of prev semester, so we have another half of the semester to test it and finally remove the old one.

However, for now, actually, we can take the risk of potentially breaking the master as the new sem hasn't started yet.

@damithc Do you think we can replace the frontend directly and accept the risk(which is quite small)?

2021-07-05 13:45 UTC, damithc commented
> However, for now, actually, we can take the risk of potentially breaking the master as the new sem hasn't started yet.
> 
> @damithc Do you think we can replace the frontend directly and accept the risk(which is quite small)?

Sure, go ahead @fzdy1914, if you are confident enough. It's fine as long as we fix any bugs before the semester starts.

2021-07-05 15:34 UTC, fzdy1914 commented
@gerhean Can you speed some time to refactor the code a bit to replace the frontend directly? Apologies for the inconvenience caused.

2021-07-06 06:39 UTC, gerhean commented
I'll try when I'm free

2021-07-17 08:57 UTC, fzdy1914 commented
@gerhean Can you give a rough estimation? Can you finish it by 2 weeks?

2021-07-17 16:34 UTC, gerhean commented
Surprisingly the checks all seem to pass and it works, but there's many warnings and outdated packages. Also the favicon seems to be missing, I'm not sure why it's not there, probably will fix soon.

2021-07-24 08:49 UTC, fzdy1914 commented
@gerhean This is a gentle reminder to continue your work. You got around 1 more weeks.

2021-07-25 08:05 UTC, gerhean commented
@fzdy1914 I think its done, please help check. Also I'm not sure if it will be better to just add markbind to the package.json.

2021-08-07 12:49 UTC, fzdy1914 approved these changes
LGTM

2021-08-07 12:49 UTC, merged