v-ramp render on visible
reposense/RepoSense pull request #1477
Opened 2021-03-12 12:29 UTC by gerhean

https://gerhean.github.io/tp-dashboard/

2021-03-21 17:52 UTC, HCY123902 commented
Can you show the time taken to load this particular report with and without this change to draw a comparison?

2021-03-22 02:24 UTC, gerhean commented
I think it is better for you to test it yourself as there are some visual differences.

2021-03-24 03:32 UTC, dcshzj approved these changes
LGTM. RAM usage looks significantly lesser on first load.

2021-03-24 03:33 UTC, dcshzj commented on frontend/src/index.pug
> +    script(src="https://unpkg.com/vue-observe-visibility/dist/vue-observe-visibility.min.js")
One thing, can you specify the exact version to use?

2021-03-25 01:56 UTC, dcshzj requested changes
As above.

2021-03-25 04:42 UTC, dcshzj approved these changes
LGTM!

2021-03-25 05:32 UTC, gerhean commented
Actually I was wondering about the purpose of specifying the rampSize in the state previously, if anyone can answer.

2021-03-29 07:51 UTC, fzdy1914 commented
@damithc Do you think the render on visible OK to you?

2021-03-29 08:16 UTC, damithc commented
> @damithc Do you think the render on visible OK to you?

Seems significantly faster. And seems memory usage is less too. Nice. 
1. But this comparison may not be fair as the first dashboard is using a much older version of RepoSense. Can we compare with the current master?
2. Are there any known downsides?

2021-03-29 10:21 UTC, gerhean commented
One obvious downside:
![image](https://user-images.githubusercontent.com/16630400/112823208-951e3100-90bb-11eb-8d71-cb2f328d4aff.png)

If you scroll too fast the ramps take about 1s to actually appear.

2021-03-29 10:30 UTC, gerhean commented
Actually when you load every single ramp, the filtering becomes slow again.

2021-03-29 11:20 UTC, damithc commented
> If you scroll too fast the ramps take about 1s to actually appear (aesthetic factor).

Might be OK if they appear fast enough, without misleading the user into thinking there are no ramps. The alternative is to show some placeholder first e.g., a `loading ...` but not sure if it will make the page slow again. 
BTW, it seems to take longer (even 2-3 seconds at times) for the ramps to appear in my home computer.

2021-03-29 11:20 UTC, fzdy1914 commented
@gerhean Can we do a mix-up? We first only render the ramps that are visible and display them to the users. Then, we start to render all other ramps.

2021-03-29 11:48 UTC, damithc commented
> @gerhean Can we do a mix-up? We first only render the ramps that are visible and display them to the users. Then, we start to render all other ramps regardless of visible or not.

Yes, that feels like best of both worlds.

2021-04-20 15:31 UTC, fzdy1914 commented
@gerhean Any update?

2021-04-20 18:41 UTC, gerhean commented
There's still a few issues to solve like the loading spinner not displaying properly.

2021-05-28 01:30 UTC, closed without merging