Remove redundant exceptions and make all tests throw generic exception
reposense/RepoSense pull request #1566
Opened 2021-07-15 13:55 UTC by FH-30

Resolves #937.

The current test code for RepoSense contains throws clauses that do not throw the generic Exception. We need to change this because when we alter what exception is thrown by any existing method used in the test code, there will be a series of changes that have to be made in the test code to prevent a compiler error. This is not only tedious but it is also against the recommended practice in SE-EDU. The present test code also contains a few methods that do not actually throw an exception but has the throws Exception clause specified which is actually redundant.

This PR makes all methods in the test folder in RepoSense throw a generic Exception and has removed all redundant exceptions being thrown by methods in RepoSense's test code. One of the methods, ```compareFileContents``` in [TestUtil.java](https://github.com/reposense/RepoSense/blob/master/src/test/java/reposense/util/TestUtil.java), results in a compiler error when it is altered to throw a generic Exception because the ```assertJson``` method in [ConfigSystemTest.java](https://github.com/reposense/RepoSense/blob/master/src/systemtest/java/reposense/ConfigSystemTest.java) catches a less generic exception type (IOException previously thrown by the ```assertJson``` method before it is altered). To mitigate this, I have altered the ```assertJson``` method in [ConfigSystemTest.java](https://github.com/reposense/RepoSense/blob/master/src/systemtest/java/reposense/ConfigSystemTest.java) to catch a generic Exception to ensure that a compiler error is not thrown.

2021-07-15 18:32 UTC, HCY123902 commented
LGTM. Just 1 minor suggestion. Although there are not many lines affected, you can actually split this into 2 separate pull requests because it seems that this pull request is handling 2 separate issues. The reason why pull request needs to be atmoic is that this can help to keep a clear record of what work is done for each individual issue and enable future contributors to know the previous progress

2021-07-15 19:03 UTC, FH-30 commented
Thanks @HCY123902 for the suggestion, I have undone the removal of redundant throws clauses in this PR and have made another PR for it [here](https://github.com/reposense/RepoSense/pull/1567).

2021-07-17 04:40 UTC, dcshzj requested changes

2021-07-17 04:40 UTC, dcshzj commented on src/test/java/reposense/parser/ArgsParserTest.java
> +            throws Exception {
I think this can fit into one line.

2021-07-17 05:06 UTC, FH-30 commented on src/test/java/reposense/parser/ArgsParserTest.java
> +            throws Exception {
Right, thanks for pointing it out!

2021-07-24 12:34 UTC, FH-30 commented
Hi @HCY123902 and @dcshzj, any updates in this PR?

2021-07-24 14:14 UTC, HCY123902 approved these changes
LGTM

2021-07-24 14:16 UTC, HCY123902 commented
@dcshzj

2021-07-28 15:00 UTC, dcshzj approved these changes

2021-07-29 15:37 UTC, fzdy1914 approved these changes

2021-08-05 16:25 UTC, merged