[#1597] Duplicate error message for missing repos
reposense/RepoSense pull request #1605
Opened 2021-12-11 11:32 UTC by Zhou-Jiahao-1998

closes https://github.com/reposense/RepoSense/issues/1597

Changed List to Set to remove duplicates without affecting performance. The order of error may change but I do not think it is an issue.

2021-12-13 08:11 UTC, gerhean commented
Can you verify that your implementation works by creating a test case?

A set of mutable objects (map) sometimes have unexpected behavior (as the hash function is not properly defined).

2021-12-13 13:28 UTC, Zhou-Jiahao-1998 commented
@gerhean I hope I am addressing your question. According to [Java 11 Map](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/AbstractMap.html#equals(java.lang.Object)), two `Map` objects are equal if the mappings are identical. Since we only add into the set and do not modify the `Map` in any ways, we can treat each `Map` as immutable. I have added a test for a quick check.

2021-12-13 13:35 UTC, gerhean commented
@Zhou-Jiahao-1998 By test I mean that you should try to recreate the situation where the duplicated error messages occurred, and ensure that the error messages indeed do not duplicate anymore.

2021-12-13 13:46 UTC, Zhou-Jiahao-1998 commented
@gerhean Alright I get what you mean now. Give me some time to figure out how to test this out without manually testing.

2021-12-19 08:07 UTC, gerhean commented
Seems to be fine but I prefer that you verify that this solution works even if the problem repo is listed in the separate files of `author-config.csv` and `repo-config.csv`

2022-01-15 06:52 UTC, dcshzj requested changes
Per above

2022-01-22 14:20 UTC, Zhou-Jiahao-1998 commented
@dcshzj Took me some time to figure out how to do system test. I added an incorrect repo in both `author-config.csv` and `repo-config.csv` on the last line. This helps to check if the duplicated error is shown.

2022-01-24 10:38 UTC, dcshzj requested changes

2022-01-24 10:38 UTC, dcshzj commented on src/test/java/reposense/model/RepoLocationTest.java
> +    public void duplicate_error_removed() {
The function name should follow our coding conventions: `featureUnderTest_testScenario_expectedBehavior()`

2022-01-25 09:20 UTC, dcshzj approved these changes
LGTM!

2022-01-26 04:14 UTC, fzdy1914 approved these changes

2022-01-26 04:26 UTC, merged