[#1603] Warn if a config file has an unknown column
reposense/RepoSense pull request #1609
Opened 2021-12-12 09:52 UTC by Zhou-Jiahao-1998

closes https://github.com/reposense/RepoSense/issues/1603

Added a new exception to handle this as using `InvalidCsvException` will not terminate the program. The check is done within `CsvParser::validateHeader`.

The original code already handles case insensitive matching of column names.

2021-12-13 08:26 UTC, gerhean commented
Thanks for taking the time to contribute!

Please read http://se-education.org/guides/conventions/github.html for commit message subject formatting, please do check out how they are formatted from past PRs as well.

2022-01-15 06:50 UTC, dcshzj requested changes

2022-01-15 06:50 UTC, dcshzj commented on src/main/java/reposense/parser/CsvParser.java
> +        StringBuilder unknownColumns = new StringBuilder();
I understand you are trying to build the string for the final output here, but I think it's better practice to store as a string array first, then use `String.join()` at the end when throwing the InvalidHeaderException.

2022-01-15 06:50 UTC, dcshzj commented on src/main/java/reposense/parser/CsvParser.java
> +                    unknownColumns.append(possible);
Per the above comment, this should be able to be simplified into something that does not need an if-else statement.

2022-01-15 06:50 UTC, dcshzj commented on src/test/resources/AuthorConfigParserTest/authorconfig_unknownHeaders_test.csv
> +Repository Location,Branch,Author's GitHub ID,Author's Emails,Author's Display Name,Author's Git Author Name,Ignore Glob
Can we change the unknown headers to be something more obvious? Something like "Totally Not A Real Header" or something better. I can't really tell directly which header should not be there.

2022-01-15 06:50 UTC, dcshzj commented on src/test/resources/GroupConfigParserTest/groupconfig_unknownHeader_test.csv
> +Group,Glob,Repository Location
Same for this as well, to make the unknown header more obvious.

2022-01-15 06:50 UTC, dcshzj commented on src/test/resources/RepoConfigParserTest/repoconfig_unknownHeaders_test.csv
> +Repository's Location,Branch,File formats,Ignore Glob List,Ignore standalone config,Ignore Commits List,Ignore Authors Lists,Shallow Cloning,Find Previous Author
Same for this as well, to make the unknown header more obvious.

2022-01-18 05:26 UTC, dcshzj approved these changes
LGTM!

2022-01-18 08:11 UTC, fzdy1914 approved these changes
feels like InvalidHeaderException should be a child class of InvalidCSVException, others LGTM

2022-01-18 12:27 UTC, Zhou-Jiahao-1998 commented
> feels like InvalidHeaderException should be a child class of InvalidCSVException, others LGTM

I agree and changes are made

2022-01-18 13:40 UTC, dcshzj commented
@Zhou-Jiahao-1998 There are still some `throws InvalidHeaderException`, can you remove them too?

2022-01-19 06:41 UTC, dcshzj commented
Looks great!

2022-01-22 06:49 UTC, Zhou-Jiahao-1998 commented
> 

Ah yes that was the whole reason for making another exception. I revert to the previous commit after realising the problem. Thanks for pointing it out!

2022-01-22 15:25 UTC, dcshzj commented
Sorry @Zhou-Jiahao-1998 I think you can revert back to the original approved commit. `InvalidHeaderException` should be a subclass of `InvalidCsvException`, and the program correctly terminates when an `InvalidCsvException` is encountered.

2022-01-23 02:15 UTC, Zhou-Jiahao-1998 commented
@dcshzj In `PepoSense::main`, the only time the program terminates because of `InvalidCsvException` is when `getRepoConfigurations` (line 61) throws it. In the same file we can find `getRepoConfigurations` (line 116). `InvalidCsvException` can only be thrown at line 118 which is when processing `repo-config`. Therefore, if the problem occurs in other config files, the program will not be terminated because the two try catch blocks below both handle `InvalidCsvException`, no exceptions will be thrown. 

Making `InvalidHeaderException` a subclass will mean that we need to have a special case for the subclass as we want it to behave differently from its parent exception. This is a violation of LSP in my opinion. Let me know what do you think.

2022-01-24 09:01 UTC, dcshzj commented
Ah I see what you mean. I think it might be a bit confusing in terms of the behavior of `InvalidCsvException`. I understand from #872 that repo-config.csv is considered a mandatory file and the other two are considered optional. This was the reasoning why any errors in repo-config.csv will terminate the program whereas errors in the other two files will only result in a warning.

I think we should retain the original behavior of terminating only for errors in repo-config.csv. Having `InvalidHeaderException` a subclass of `InvalidCsvException` should now be fine, since they now share the same behavior.

2022-01-25 04:21 UTC, Zhou-Jiahao-1998 commented
@dcshzj Do you think we should ask prof for his inputs as he opened this issue?

2022-01-25 08:05 UTC, damithc commented
> @dcshzj Do you think we should ask prof for his inputs as he opened this issue?

Guys, what exactly do you want my input on? i.e., what's the question, what are the options, pros and cons of each, your recommendation (if any)?

2022-01-25 08:43 UTC, Zhou-Jiahao-1998 commented
@damithc The issue here is that I added a new `InvalidHeaderException` for the case where any config file contains unknown columns. Throwing this exception will terminate the program gracefully and output the error message.

The other option we have is to follow the current format of `InvalidCsvException` and make `InvalidHeaderException` a subclass of `InvalidCsvException`. The program is only terminated if the error is thrown from parsing `repo-config`. This is how the program handles parsing errors in config files now.

Using the first approach, we will terminate the program as long as there is an unknown column. I personally prefer this option as mentioned in the issue. It is likely a mistake from the user side and the mistake might affect the actual output.

If we use the second approach, we will have a smoother behaviour as all exceptions behave the same way in different config files. It is also logical to think that `InvalidHeaderException` can be a subclass of `InvalidCsvException`.

2022-01-25 10:38 UTC, damithc commented
> @damithc The issue here is that I added a new `InvalidHeaderException` for the case where any config file contains unknown columns. Throwing this exception will terminate the program gracefully and output the error message.
> 
> The other option we have is to follow the current format of `InvalidCsvException` and make `InvalidHeaderException` a subclass of `InvalidCsvException`. The program is only terminated if the error is thrown from parsing `repo-config`. This is how the program handles parsing errors in config files now.
> 
> Using the first approach, we will terminate the program as long as there is an unknown column. I personally prefer this option as mentioned in the issue. It is likely a mistake from the user side and the mistake might affect the actual output.
> 
> If we use the second approach, we will have a smoother behaviour as all exceptions behave the same way in different config files. It is also logical to think that `InvalidHeaderException` can be a subclass of `InvalidCsvException`.

The actual implementation details, I'll leave you to decide.
But I can give inputs from external behavior PoV. The question seems to be: should we (a) terminate or (b) warn only, if there is an unknown column.

Pros of terminating: the user will have no choice but to fix.
Cons: the user will not be able to keep extra columns in the file, e.g., for reference purposes.

I'm leaning slightly towards terminating, as it avoids the situation of a user missing the warning and a mistake in the column name going unnoticed for a while.

2022-02-04 07:51 UTC, dcshzj approved these changes
Yup I think let's keep it this way where `InvalidHeaderException` is a separate class from `InvalidCsvException`.

2022-02-04 07:52 UTC, dcshzj commented
@fzdy1914 Can you confirm if this is a good design?

2022-02-04 08:15 UTC, fzdy1914 approved these changes

2022-02-07 01:58 UTC, merged