Remove unused variables in Java files
reposense/RepoSense pull request #1673
Opened 2022-02-15 17:04 UTC by chan-j-d

Commit message:
```
Let's clean up unused fields and local variables. 
```

2022-02-16 02:13 UTC, yhtMinceraft1010X requested changes

2022-02-16 03:19 UTC, chan-j-d commented on src/test/java/reposense/parser/ArgsParserTest.java
> -    private static final ZoneId TIME_ZONE_ID = TestUtil.getZoneId(DEFAULT_TIMEZONE);
Thanks for catching this!

2022-02-16 03:19 UTC, chan-j-d commented on src/main/java/reposense/parser/ArgsParser.java
> -    private static final String MESSAGE_IGNORING_REPORT_CONFIG_SINCE_DATE =
Yeah I noticed it. But it seems somewhat strange that this made it in to the code base even though the actual feature is likely a long way off. I think we should remove it here and add only add it in when #634 is completed.

2022-02-16 03:30 UTC, chan-j-d commented on src/main/java/reposense/parser/ArgsParser.java
> -                    + "together.";
> While reviewing this, I noticed that line 270 in the same file suggests that the --repos flag will override the --config flag, although the User Guide cli.md only states that both flags cannot be used with each other.

Interesting. It's something I just assumed was there. I think it'll be more appropriate in a separate PR.

2022-02-16 09:29 UTC, yhtMinceraft1010X commented on src/main/java/reposense/parser/ArgsParser.java
> -                    + "together.";
In that case, I'll raise it up as a separate issue.

2022-02-17 10:01 UTC, chan-j-d commented
@yhtMinceraft1010X I've updated accordingly.

2022-02-17 10:37 UTC, yhtMinceraft1010X requested changes
Nice job with the refactoring.

For spelling consistency, I recommend choosing either `TIME_ZONE` or `TIMEZONE` and also renaming `DEFAULT_TIMEZONE` as `DEFAULT_TIMEZONE_STRING`, since someone might think that `DEFAULT_TIMEZONE` is the `ZoneId` object rather than the `String`.

2022-02-17 10:43 UTC, chan-j-d commented
> For spelling consistency, I recommend choosing either `TIME_ZONE` or `TIMEZONE` and also renaming `DEFAULT_TIMEZONE` as `DEFAULT_TIMEZONE_STRING`, since someone might think that `DEFAULT_TIMEZONE` is the `ZoneId` object rather than the `String`.

Makes sense, I've updated accordingly

2022-02-17 11:46 UTC, yhtMinceraft1010X approved these changes
LGTM

2022-02-17 11:57 UTC, chan-j-d commented
oops, active-developers, please ignore this

2022-02-19 10:52 UTC, dcshzj approved these changes
LGTM! This should not affect the logic of the software, so I'm going to directly merge this.

2022-02-21 02:30 UTC, merged