Update ternary operator style guide
reposense/RepoSense pull request #1688
Opened 2022-02-24 13:27 UTC by yhtMinceraft1010X

Proposed Commit Message:
```
Ternary style guide refers to the Date class, which has been replaced
with LocalDateTime in the code.

Let's update the style guide example accordingly.
```

2022-02-24 13:47 UTC, damithc commented
Guys, a side note: 
Try not to create lengthy style guides as this becomes an additional maintenance burden. We don't want every NUS-OSS project to have their own lengthy style guide as it's going to be a waste of effort and will make it harder for students to work in multiple projects.

It's best to follow existing style guides as a base (e.g., https://se-education.org/guides/) and point to other more comprehensive guide e.g., those provided by Google) as a fallback when the base doesn't cover something.

2022-02-28 04:09 UTC, chan-j-d reviewed
I'm not entirely sure if it is necessary to follow the similar line of code in the codebase itself. I personally think the original example is sufficient to illustrate the idea of ternary operators and I would like to know your thoughts on this.

2022-03-05 02:27 UTC, dcshzj requested changes
I think it should be okay to update the Date to LocalDateTime to match the codebase, in case of curious people who want to find this line of code in the codebase. It is not a hard requirement however, so it should not add to the maintenance burden.

2022-03-05 02:27 UTC, dcshzj commented on docs/dg/styleGuides.md
> +       : commitInfos.get(0).getTime();
I think this should be 8 spaces?

2022-03-06 17:26 UTC, chan-j-d approved these changes
LGTM!

2022-03-07 03:24 UTC, dcshzj approved these changes
LGTM! Will merge since it's just documentation changes.

2022-03-09 11:42 UTC, merged