[#1739] Add schema for json data files
reposense/RepoSense pull request #1740
Opened 2022-03-30 06:46 UTC by Zhou-Jiahao-1998

Fixes #1739 

## Proposed commit message

```
There is no json schema for the data files generated. This can
be difficult to debug when the file is corrupted or when backend
generates a wrong json file.

Let us add schema file to our json files to make future debugging
easier.
```

## Other information

2022-04-02 12:39 UTC, yhtMinceraft1010X requested changes
This sounds like a great idea. I think the instructions on how to use this should be included in the DG, such as `workflow.md`.

2022-04-02 12:44 UTC, yhtMinceraft1010X commented
One concern I have though is that the plugin described in the given guide is only available on IntelliJ IDEA Ultimate Edition, which is a paid product. Not every developer may have the paid version and consequently won't be able to make use of this feature.

2022-04-04 03:47 UTC, Zhou-Jiahao-1998 commented
> One concern I have though is that the plugin described in the given guide is only available on IntelliJ IDEA Ultimate Edition, which is a paid product. Not every developer may have the paid version and consequently won't be able to make use of this feature.

Yes that is a valid concern. I have added the instruction for VS Code in `workflow.md`.

2022-04-07 11:39 UTC, yhtMinceraft1010X approved these changes
LGTM

2022-04-07 11:41 UTC, yhtMinceraft1010X commented on docs/dg/workflow.md
> +* If you are using **Visual Studio Code**, open the `.json` data file. Using `summary.json` as an example, add `"$schema": "../frontend/json-schema/summary-schema.json"` to the start of json. If you
Will adding the `$schema` line affect the way the frontend processes the json?

2022-04-08 11:27 UTC, gerhean commented
Will this schema be used for typescript as well? I rather not have multiple schemas.

2022-04-08 21:30 UTC, gok99 reviewed
Just had a thought (this could probably be explored separately if at all): would it be a good idea to generate these automatically from the Java classes which can act as a single truth source? Haven't looked into this too much but maybe this is useful: http://wilddiary.com/generate-json-schema-from-java-class/

2022-04-08 21:30 UTC, gok99 commented on frontend/json-schema/authorship-schema.json
> +{
I'm not sure if non-required fields need to be included here, but there is also a field `isBinary` (and `isIgnored` added in #1647) that are only serialized if true.

See: [FileResult.java](https://github.com/reposense/RepoSense/blob/2b864022bbf5db55ae9d4f96eaf0a70e961646f5/src/main/java/reposense/authorship/model/FileResult.java)

2022-04-09 06:33 UTC, gerhean commented
I agree with @gok99 that I would rather have a single file which both the frontend and java can verify json against.

However my priority for now is Typescript integration.

2022-04-10 12:21 UTC, closed without merging