[#1118] Change restriction for author names to disallow only empty names
reposense/RepoSense pull request #1797
Opened 2022-06-24 09:40 UTC by bingsen0806

Fixes #1118 

```
AnnotatorAnalyzer: Remove restriction for author name in @@author tags

RepoSense does restrictive checks for valid author names.

Following the discussion, it is recommended to remove such restrictive
checks so that names such as "--validName--" will be allowed.

Let's remove the regex pattern for checking author names and
update test cases accordingly so that all non-blank Strings are treated
as valid author names
```

2022-06-26 09:23 UTC, chan-j-d requested changes
Good work on your first PR! Do take a look at the suggested changes

2022-06-26 09:23 UTC, chan-j-d commented on src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java
> +    private static final Author VALID_AUTHOR_IF_REGEX_CHECK_ABSENT_1 =
Not too sure I understand the purpose of this specific `Author` object.

2022-06-26 09:23 UTC, chan-j-d commented on src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java
> +        Assertions.assertTrue(AnnotatorAnalyzer.extractAuthorName(line).isPresent()); // author name is "fakeAuthor-->"
Would it make more sense to remove the `invalidAuthorName` test methods altogether? And perhaps add the stranger but now accepted author names like `--authorname--` to the `matchCommentPattern` test cases to ensure that they are parsed correctly.

2022-07-23 14:26 UTC, dcshzj commented
Hi @bingsen0806, any updates to this PR?

2022-09-30 00:31 UTC, closed without merging