1818 input builder local repo system test
reposense/RepoSense pull request #1821
Opened 2022-08-07 10:38 UTC by lawwm

Fixes #1818 

## Proposed commit message

```
Currently, all test cases within LocalRepoSystemTest uses String.format().

Hence, change cli input of test cases within LocalRepoSystemTest to use the InputBuilder class. 
```

## Other information

Removed `addQuotationMarksToPath` within `InputBuilder` for the `addRepos` and `addOutput` functions. I'm not entirely sure about the purpose of the quotation marks as the commands `./gradlew systemtest` and `./gradlew test` still work regardless.

However, adding quotations marks for a local directory such `-o "local-test"` fails while `-o local-test` works. Please inform me if I should revert back to adding the quotation marks and find another workaround.

2022-08-07 12:07 UTC, SkyBlaise99 commented
There is a 72 characters per line hard limit for Proposed commit message. Just make it a new line at about 70 chars.

2022-08-07 12:21 UTC, SkyBlaise99 requested changes
Good job. Please see the comments for the changes. You can also provide reasoning if you think some parts cannot / should not be changed 😄

2022-08-07 12:21 UTC, SkyBlaise99 commented on src/systemtest/java/reposense/LocalRepoSystemTest.java
> +    private static final String EARLIEST_COMMIT_DATE = "d1";
You can use `SinceDateArgumentType.FIRST_COMMIT_DATE_SHORTHAND` instead.

2022-08-07 12:21 UTC, SkyBlaise99 commented on src/systemtest/java/reposense/LocalRepoSystemTest.java
>          runTest(cliInput, "LocalRepoSystemTest/testSameFinalDirectory");
A bit weird to have some preprocessing here and then another `String[] args = commandArgs.split(" ");` before `RepoSense.main(args);`.

I suggest an alternative way which is to pass the `inputBuilder` to `runTest()`. You can refer to [this](https://github.com/reposense/RepoSense/pull/1816/files#diff-59400ca2297b765e07badbf3424d7ac8fdb8237d902ea99ad60a581447f9b05cR175) to see how it is done.

2022-08-07 12:21 UTC, SkyBlaise99 commented on src/systemtest/java/reposense/LocalRepoSystemTest.java
>          String relativePathForTesting = "parent1/../parent1/./test-repo";
Can just inline and remove this variable.

2022-08-07 14:35 UTC, SkyBlaise99 commented
> However, adding quotations marks for a local directory such -o "local-test" fails while -o local-test works. Please inform me if I should revert back to adding the quotation marks and find another workaround.

Use `InputBuilder` with `translateCommandline()` to pass the test cases. I see you have changed to that already, I think you can try to revert back the changes and test it out again.

2022-08-07 14:50 UTC, lawwm commented
Thank you, `translateCommandline()` seems to solve the quotation issue.

2022-08-08 01:49 UTC, SkyBlaise99 commented
No problem. Do remember to resolve all requested changes before asking for a review again.

2022-08-09 06:21 UTC, SkyBlaise99 requested changes
Looking good, just remember to remove unused variables.

2022-08-09 06:21 UTC, SkyBlaise99 commented on src/systemtest/java/reposense/LocalRepoSystemTest.java
> +    private static final String EARLIEST_COMMIT_DATE = "d1";
Remember to remove unused variables.

2022-08-09 06:24 UTC, SkyBlaise99 commented
Next time after you done resolving the changes, click the button here (should be red for you) and there should be an option to request for review again to alert us. Or you can also @ us here or in Slack to notify us.

![image](https://user-images.githubusercontent.com/69448615/183579091-0d88162f-33bb-4daa-97e2-7e5e7d322175.png)

2022-08-09 10:19 UTC, lawwm commented
![image](https://user-images.githubusercontent.com/41231584/183624015-bff64733-4572-4ac6-905b-99e772f5dadf.png)
Sorry, missed out on the unused variable. Also, I'm not sure why but the ui doesn't display any changes when i click the `re-request review` button.

2022-08-09 11:16 UTC, chan-j-d approved these changes
LGTM!

2022-08-09 13:32 UTC, SkyBlaise99 approved these changes
LGTM! Great job.

2022-08-11 15:16 UTC, dcshzj approved these changes
LGTM!

2022-08-13 13:00 UTC, merged