Add guard against glob processing in generating authorship summary
reposense/RepoSense pull request #1839
Opened 2022-10-09 10:20 UTC by lawwm

Fixes #1594 

## Proposed commit message

```
Ignored directories still undergo heavy processing despite 
being ignored. 

Add guard clauses in authorship summary generation to prevent
ignored files from being processed.
```

## Other information

Tested it on a directory with 151mb of pdf documents.

*Without* globs: 
`05:52:10 - Elapsed processing time: 1 minute(s) 58.73 second(s)`

*With* globs:
`05:48:13 - Elapsed processing time: 36.43 second(s)`

2022-10-10 08:21 UTC, damithc commented
@lawwm is this PR ready for review?

2022-10-10 14:19 UTC, damithc commented
@reposense/active-developer for your review ...

2022-10-15 21:05 UTC, chan-j-d requested changes
Thanks for doing up! Some minor suggested changes.

Would also like to check the exact parameters that you used to demonstrate the performance improvement as I have been unable to replicate it. Thanks!

2022-10-15 21:05 UTC, chan-j-d commented on src/test/java/reposense/authorship/FileInfoExtractorTest.java
> +    }
I think this is missing the check for files that are correctly ignored, such as some `.md` files or `newPos/*.java` files.

2022-10-15 21:05 UTC, chan-j-d commented on src/test/java/reposense/authorship/FileInfoExtractorTest.java
> +        Assertions.assertFalse(isFileExistence(Paths.get("renamedFile.java"), files));
This is also missing the check that the `README.md` file is not present.

2022-10-16 09:38 UTC, lawwm commented
> Thanks for doing up! Some minor suggested changes.
> 
> Would also like to check the exact parameters that you used to demonstrate the performance improvement as I have been unable to replicate it. Thanks!

Thnak you for the review. I added the link to the repositories that I used to measure performance. I stored the `repo-config.csv` that I ran Reposense on within the repo.

2022-10-16 15:56 UTC, chan-j-d approved these changes
LGTM for large file sizes. I've tested it and it seems to do well.

However, I think the PR actually does not directly address #1594 which seems to be more to do with large number of small files.

 Try analyzing https://github.com/AY2122S1-CS2113T-W12-2/tp/ with the arguments `-s d1` (since day 1). The `data/**` files are no longer in the repo but you can still see them in the commit history and so they are still analyzed. Including `data/**` in the config removes them from analysis but the analysis time I had is about the same with this implementation and the master branch. Can consider looking into that if you have the time.

Consider changing the PR description as well to reflect this as well.

2022-10-19 06:44 UTC, lawwm commented
> However, I think the PR actually does not directly address #1594 which seems to be more to do with large number of small files.

Thank you for catching that, I failed to notice it and will be looking into it.

2022-10-19 06:53 UTC, chan-j-d commented
@lawwm thanks! Do create a separate PR for that though as I think this change is a pretty good standalone change

2022-10-26 15:56 UTC, lawwm commented
Hi, I'm not sure if I'm right but it seems to me like the analysis time for https://github.com/AY2122S1-CS2113T-W12-2/tp/ is the same because the time required for processing the commits is negligible.

I tested using two factors, using the ignore globs and using a different date. 

`--since d1` includes the `data/**` files in the commit history, while `--since 2/10/2021` excludes the `data/**` files in the commit history (both the addition and deletion commits).
```
--since d1 (with ignore globs)
11:07:33 - Elapsed processing time: 24.72 second(s)
11:08:31 - Elapsed processing time: 22.87 second(s)

--since d1
10:56:22 - Elapsed processing time: 21.53 second(s)
11:18:43 - Elapsed processing time: 24.44 second(s)

--since 2/10/2021 (with ignore globs)
11:09:14 - Elapsed processing time: 19.34 second(s)
11:09:49 - Elapsed processing time: 20.99 second(s)

--since 2/10/2021
11:05:40 - Elapsed processing time: 21.46 second(s)
11:17:14 - Elapsed processing time: 22.82 second(s)
```

Codewise, the ignore globs for generation of commit summary are used during a `GitLog.getWithFiles(config, author)` command which occurs quite early in the process within the `generateCommitSummary`, so the ignore globs does seem to ignore processing of commits.

Please correct me if I'm wrong or if I've missed out on something, thank you.

2022-10-26 16:35 UTC, chan-j-d commented
I'm not too sure what the exact issue and time disparity is supposed to be as well as I only checked the files in the repo in question. You might be able to get more insight by raising the question on the issue directly and tagging.

One possibility might be that the poor performance is specifically while the files themselves are present and not deleted yet since the date of the issue was raised just 1 day after the files were actually removed.

2022-11-29 14:33 UTC, dcshzj approved these changes
LGTM!

2022-12-02 14:45 UTC, merged