[#1879] Mismatch between system test case and actual RepoSense behavior
reposense/RepoSense pull request #1911
Opened 2023-02-19 18:13 UTC by sikai00

Fixes #1879 
Possibly part of #1873 

### Proposed commit message

```
Due to legacy reasons, the test mode flag was added in order to allow 
systemtest to pass. However, systemtest was previously failing because 
the json file were incorrect and should not have included the addition 
of authors not listed in author config files.

In reality, RepoSense's behavior is correct and thus do not require 
hasAuthorConfiguration to be set to false for all the systemtest.

Let's update the json files to more accurately match the actual 
behavior of RepoSense. Let's also remove the setting of 
hasAuthorConfiguration to false if test mode is enabled.
```

### Other information

Should only be merged after #1910.

2023-02-27 03:32 UTC, dcshzj commented
Are you able to adjust the PR title to be more of an action? The title should describe what the PR will do/change instead of what the issue was. Thanks!

2023-03-04 20:45 UTC, sikai00 commented
> Are you able to adjust the PR title to be more of an action? The title should describe what the PR will do/change instead of what the issue was. Thanks!

I have updated the title as per your request, I believe this should more accurately reflect what this PR is doing!

2023-03-07 17:59 UTC, ckcherry23 requested changes
Hi @sikai00, I think there are some conflicts that need to be resolved as the structure of `commits.json` files had to be modified in #1882.

2023-03-07 19:52 UTC, ckcherry23 approved these changes
LGTM!

2023-03-09 08:27 UTC, chan-j-d approved these changes
LGTM!

2023-03-09 08:27 UTC, chan-j-d commented on docs/dg/cli.md
> -with `AnnotatorAnalyzer.findAuthorInLine()` where `AuthorConfiguration.hasAuthorConfigFile()` is called.
Great catch for this, I actually forgot this statement was there.

2023-03-09 08:28 UTC, chan-j-d commented
On a tangentially related note, I think we should create an issue regarding the test mode flag, to see if there's any other uses for it and otherwise we should consider removing it

2023-03-11 02:04 UTC, yhtMinceraft1010X approved these changes
LGTM

2023-03-13 02:01 UTC, dcshzj commented
@sikai00 Are you able to resolve the file conflicts? Thanks!

2023-03-13 02:29 UTC, sikai00 commented
> @sikai00 Are you able to resolve the file conflicts? Thanks!

I have merged and resolved the conflict. Thanks for letting me know!

2023-03-13 02:35 UTC, merged