[#1996] Update frontend documentation
reposense/RepoSense pull request #1999
Opened 2023-05-01 12:39 UTC by ckcherry23

Fixes #1996 

### Proposed commit message
```
The HTML report documentation is outdated after changes introduced in 
recent PRs. This will make it difficult for new contributors to 
understand the frontend codebase.

Let us update the documentation and puml diagrams to match the new 
files and architecture. Let us also comment out the links used as 
examples to avoid broken links. 
```

### Other information
- Updated file names in `report.md`
- Updated all `.puml` diagrams for the Report Architecture 
- Commented out links in `authorConfigSyntax.md` to avoid broken links

2023-05-01 13:43 UTC, HCY123902 commented on docs/dg/report.md
>  ## Javascript and Vue files
I think it should be changed to `TypeScript and Vue files` instead

2023-05-01 14:03 UTC, HCY123902 approved these changes

2023-05-02 04:17 UTC, yhtMinceraft1010X requested changes

2023-05-02 04:17 UTC, yhtMinceraft1010X commented on docs/dg/report.md
> -![report architecture](../images/report-architecture.png)
Line 15: For the report architecture, we haven't been able to get it to auto-render as puml for quite some time, so you need to manually generate the new `report-architecture.png` image.

2023-05-03 04:59 UTC, yhtMinceraft1010X approved these changes
LGTM

2023-05-05 02:38 UTC, merged