Add show more button for error messages
reposense/RepoSense pull request #2105
Opened 2024-01-30 06:44 UTC by jonasongg

Fixes #2098 

### Proposed commit message

```
Add show more button for error messages

Currently, if there are a lot of error messages, it can block the rest
of the page to the point where users may thing the report failed to
generate at all.

Let's hide extra messages automatically add a show more button if there
are more to display the messages in full.```

### Other information

Currently, I opted for an easier JS implementation of the feature that displays the button if the number of error messages are above 4. About this, I wanted to ask what the best place would be to put a constant that defines this number (maximum number of error messages displayed without showing more).

Regarding the design of the show more button, I wanted to also get some thoughts on what would work best for RepoSense:
![image](https://github.com/reposense/RepoSense/assets/120372506/cea5d08b-135f-4c80-bd5d-4d2be567a709)

![image](https://github.com/reposense/RepoSense/assets/120372506/b19a329b-4f8b-49dd-8d08-a6ba69aa74b2)
(default <a>, bad contrast)

![image](https://github.com/reposense/RepoSense/assets/120372506/9b20d605-ccd9-4638-9858-cc8ead24caaa)
(default MUI text button)

Lastly, with JS, the transition when clicking show more is visually a bit jarring as the new elements appear programmatically. If needed, I can investigate a way to better animate showing more through CSS, which would also eliminate the need to have a constant to define the number of error messages displayed by default (preliminarily, this would involve adding a transition to max-height).

2024-01-30 06:55 UTC, sopa301 approved these changes
LGTM! I think I like the blue option more because it's distinct from the surrounding colours. Also, the rest of RepoSense also uses blue for toggles.

2024-01-30 08:15 UTC, asdfghjkxd requested changes
Good work on the PR! 

However, it seems like CI is failing due to some linting mistakes!

2024-01-30 08:15 UTC, asdfghjkxd commented on frontend/src/views/c-summary.vue
> +      a.error-message-box__show-more(v-else v-on:click="toggleErrorShowMore()") SHOW LESS...
CI seem to have indicated this area as a potential violation of certain linting rules, might warrant further investigation to know what went wrong!

2024-02-02 09:56 UTC, jonasongg commented
@sopa301 @asdfghjkxd Thanks for the insight! Fixed the linting issue also

2024-02-02 18:33 UTC, ckcherry23 requested changes

2024-02-02 18:33 UTC, ckcherry23 commented on frontend/src/views/c-summary.vue
> +    .error-message-box__show-more-container(v-if="Object.keys(errorMessages).length >= 4")
This should not contain `=` as by default 4 errors are shown according to line 80. Else, we could also change it to show only 3 errors by default.

```suggestion
    .error-message-box__show-more-container(v-if="Object.keys(errorMessages).length > 4")
```

2024-02-02 18:33 UTC, ckcherry23 commented on frontend/src/styles/style.scss
> +
Can we move these styles to the view file instead of the global styles file? We could also move it later to a dedicated component to display errors.

2024-02-02 18:54 UTC, ckcherry23 commented
@jonasongg Thanks for tacking this issue!

> About this, I wanted to ask what the best place would be to put a constant that defines this number (maximum number of error messages displayed without showing more).

For now, I think we can define it in the view file and later move it to a dedicated Vue component.

> Regarding the design of the show more button, I wanted to also get some thoughts on what would work best for RepoSense.

Currently, the 'Show More' button takes up a lot of vertical space at the bottom of the error box. Moreover, we do not expect most users to click on 'Show More' so it can be more subtle. I think what would work better to fit in with the compact style of RepoSense is using a right-aligned button styled like a red link.

![image](https://github.com/reposense/RepoSense/assets/68203159/a4d3db34-1f40-4e58-8502-2810e2b65f29)

> Lastly, with JS, the transition when clicking show more is visually a bit jarring as the new elements appear programmatically. If needed, I can investigate a way to better animate showing more through CSS, which would also eliminate the need to have a constant to define the number of error messages displayed by default (preliminarily, this would involve adding a transition to max-height).

I think the transition isn't too bad but if you're interested in implementing smoother transitions, please go ahead!

2024-02-03 04:36 UTC, damithc commented
One other comment about the UI: I feel the fact that some errors have been omitted should be more apparent. The current `Show more` appears like a regular UI control that people will automatically ignore.

For example, the last line of error message could be 
> Remaining error messages omitted to save space. [Show all ...]()

What do you all think? Other alternatives?

2024-02-03 10:04 UTC, ckcherry23 commented
> For example, the last line of error message could be
> 
> > Remaining error messages omitted to save space. Show all ...

Just some mockups for discussion:

![image](https://github.com/reposense/RepoSense/assets/68203159/e878d95e-ec20-4e44-8fac-b24477cba448)
![image](https://github.com/reposense/RepoSense/assets/68203159/0de293dd-3ec7-4154-ac0b-7dfad011b6e6)

2024-02-03 11:04 UTC, damithc commented
> Just some mockups for discussion:
> 
> ![image](https://private-user-images.githubusercontent.com/68203159/302028251-e878d95e-ec20-4e44-8fac-b24477cba448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTg1MTcsIm5iZiI6MTcwNjk1ODIxNywicGF0aCI6Ii82ODIwMzE1OS8zMDIwMjgyNTEtZTg3OGQ5NWUtZWMyMC00ZTQ0LThmYWMtYjI0NDc3Y2JhNDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDExMDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYWViNzA4YmFiZTBjNWE5YTIxOTg2NGY4OGVjMTg1ZTdjOTRmZWQyZGUwOWYxOWMxNWM3ZmUyYmYxNGIwMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eDvZXIbMWywlMrUIKR4CLPvFXa-ZrPctoZp_ic9lfEw) ![image](https://private-user-images.githubusercontent.com/68203159/302028264-0de293dd-3ec7-4154-ac0b-7dfad011b6e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTg1MTcsIm5iZiI6MTcwNjk1ODIxNywicGF0aCI6Ii82ODIwMzE1OS8zMDIwMjgyNjQtMGRlMjkzZGQtM2VjNy00MTU0LWFjMGItN2RmYWQwMTFiNmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDExMDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYTU4YWY0ZTEwYmM4NGFlOWY2ZDczYmQ5ODkzODM1NzJmZTU2MWZmZGQ5ZjNhYWQ1MDkxODgzMDFmMGUxZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-UiwlQNrlHr1598pbzVYY6V1p3bExce1c4i9qGxo5k)

Thanks @ckcherry23 I'm OK with either. Will leave you all to decide.

2024-02-05 04:32 UTC, jonasongg commented
@ckcherry23 Added the changes as specified!

2024-02-05 04:47 UTC, jonasongg commented
@ckcherry23 Wondering if I should add some tests in chartView_errorSummary_messageBox.cy.js to test this show more button; if I do, then I will need to add some repos to summary.json

2024-02-05 04:59 UTC, ckcherry23 commented
Yes, it would be great if we added a test case to test this behaviour!

However, adding repos to `summary.json` may cause other test cases to break so we try to avoid making any changes to it (the `RepoSense/cypress` branch) unless absolutely necessary.

In your case, would it be okay to show only 3 errors by default?

2024-02-06 14:49 UTC, jonasongg commented
If I'm not wrong, the default cypress configuration will only result in one error message, so I'm not too sure on how best to test this!

2024-02-06 14:53 UTC, ckcherry23 commented
> If I'm not wrong, the default cypress configuration will only result in one error message, so I'm not too sure on how best to test this!

@jonasongg Okay, I thought the Cypress configuration had 4 errors, which is why I suggested the default of 3.

In that case, let's make changes to the `cypress` branch. You can go ahead and add more repos for analysis to the branch locally and see if all the Cypress tests pass, and fix any breaking tests.

2024-02-15 06:27 UTC, jonasongg commented
@ckcherry23 Sorry for the late update, just added the aforementioned tests!

2024-02-16 16:40 UTC, ckcherry23 commented
@jonasongg Please edit the title of the PR to include the issue number

2024-02-16 16:46 UTC, ckcherry23 commented on frontend/cypress/tests/chartView/chartView_errorSummary_messageBox.cy.js
> +  it('number of error messages', () => {
We could make this test case name more descriptive
```suggestion
  it('can be expanded and collapsed if count > 4', () => {
```

2024-02-17 06:26 UTC, jonasongg commented
@ckcherry23 Made the changes! Thanks

2024-02-17 06:52 UTC, vvidday requested changes

2024-02-17 06:52 UTC, vvidday commented on frontend/src/views/c-summary.vue
> +    .error-message-box__show-more-container(v-if="Object.keys(errorMessages).length > 4")
Functionality looks good! Can we store the "4" in a variable within this file as mentioned by @ckcherry23?

2024-02-17 12:42 UTC, jonasongg commented
@vvidday @ckcherry23 I added the variable in data() as I'm not too sure what the idiomatic way to define constants in our Vue files are, let me know if I should change it!

2024-03-04 03:59 UTC, jonasongg commented
@vvidday thanks for pointing this out! a very simple fix for most of these tests would like you suggested to remove the `.should(be.visible)` assertion in the tests, but i'm not sure if this is the right way to fix them? another way could be to scroll down so that the elements are visible

2024-03-09 14:41 UTC, sopa301 commented
We can either use the `exist` [assertion](https://docs.cypress.io/guides/references/assertions) or we can use [`scrollIntoView`](https://docs.cypress.io/api/commands/scrollIntoView) as you mentioned. I think it would be better to use `scrollIntoView` because it would more closely follow an actual user's interaction.

2024-03-11 06:57 UTC, ckcherry23 approved these changes
LGTM!

2024-03-11 12:35 UTC, vvidday approved these changes
Thanks for the changes, LGTM!

2024-03-14 04:35 UTC, asdfghjkxd approved these changes
LGTM!

2024-03-14 04:37 UTC, merged