[#2001] Extract c-zoom-commit-message component from views/c-zoom
reposense/RepoSense pull request #2132
Opened 2024-02-20 15:44 UTC by sopa301

Part of #2001.

### Proposed commit message

```
Many of the frontend files are difficult to navigate through due to the
large file sizes. As we add more features to the frontend, it is
getting harder to maintain. This is also very unfriendly towards new
contributors. 

Let us break down frontend files in a logical manner, continuing with
extracting c-zoom-commit-message from views/c-zoom.
```

### Other information

2024-03-16 09:40 UTC, sopa301 commented on frontend/src/components/c-zoom-commit-message.vue
> +    },
Nope! Thanks for catching it!

2024-03-17 07:31 UTC, ckcherry23 approved these changes
LGTM! Thanks for helping with the componentization.

2024-03-19 02:47 UTC, MarcusTXK requested changes
Looks great, nice job with this, it makes `c-zoom.vue` alot easier to read. I have just a minor nitpick with the spacing of the `methods`, as some have an extra new lines after them and others do not.

Shall we standardize it as no spaces between the methods?

2024-03-20 13:08 UTC, sopa301 commented
Okay, should we add a [linting rule](https://eslint.style/rules/ts/lines-between-class-members) for that?

2024-03-26 03:41 UTC, MarcusTXK commented
> Okay, should we add a [linting rule](https://eslint.style/rules/js/padding-line-between-statements) for that?

Yup sure, feel free to create an issue for this, I think that will definitely help with consistency

2024-03-26 03:41 UTC, MarcusTXK approved these changes
LGTM

2024-03-27 22:11 UTC, merged