[#2145] Dockerisation of RepoSense
reposense/RepoSense pull request #2149
Opened 2024-03-09 15:01 UTC by asdfghjkxd

Part of #2145 

### Proposed commit message

```
Currently, there are some issues with regard to consistent testing of
code, especially for the frontend code, due to the difference in
environments where the test cases are run (developer's machine VS
Github Action's workers). This inconsistency in testing results makes
it hard for us to really distinguish false negatives/false positives.

Moreover, this inconsistency in the environment where RepoSense is
installed may also result in dependency issues.

In this PR, a proof-of-concept Dockerfile and docker-compose.yml file
will be provided first to test the viability of such an integration
into RepoSense. Future implementations would see further integration of
Docker into Github Actions, more complicated Docker build processes and
tests and documentation on how to maintain these Docker files and
builds.

Let's move to integrate Docker and Docker Compose into RepoSense to
mitigate and potentially solve some of the aforementioned issues, by
providing users and developers a more standardised environment where
they can run or test RepoSense.
```

### Other information

This PR is part of the following steps outlined in the parent issue:

- [X] Create Dockerfile for creation of Docker containers
- [X] Create docker-compose.yml for the orchestration of our Docker containers for testing and deployment

2024-03-15 13:52 UTC, asdfghjkxd commented
Do note that the Docker containers currently do not conduct frontend tests using cypress, even though the dependencies are installed on the base Ubuntu containers, as they are consistently failing CI. Will look into the cause and update this thread once I have isolated the cause of the error.

2024-03-18 04:23 UTC, sopa301 requested changes
LGTM! We just need to fix the Cypress issues.

2024-03-18 04:23 UTC, sopa301 commented on docker/Dockerfile.ubuntu2204
> +LABEL "os.version"="20.04"
This should probably be 22.04.
```suggestion
LABEL "os.version"="22.04"
```

2024-03-18 04:23 UTC, sopa301 commented on .github/workflows/docker.yml
> +      # - name: Upload Code Coverage (Java 8)
Is this going to be re-added?

2024-03-18 04:23 UTC, sopa301 commented on docker-compose.yaml
As discussed, since we're not using this for the CI, we can probably put this in a folder marked for local testing.

2024-03-18 04:58 UTC, asdfghjkxd commented
As mentioned in issue #2145, we are not pursuing this idea, hence I am closing out this PR.

2024-03-18 04:58 UTC, closed without merging