[#2158] Add More Documentation for Title Component
reposense/RepoSense pull request #2159
Opened 2024-03-16 09:23 UTC by sopa301

Fixes #2158.

### Proposed commit message

```
Add More Documentation for Title Component

The documentation for the title component is sparse. Adding more
details on how to use it will make it easier for users to add their own
titles to their reports.

Let's update the documentation to include a section for the title
component, and add the title component to the default view.
```

### Other information

2024-03-25 12:06 UTC, asdfghjkxd approved these changes
LGTM!

2024-03-27 21:19 UTC, ckcherry23 requested changes

2024-03-27 21:19 UTC, ckcherry23 commented on docs/ug/customizingReports.md
> +The title can render a combination of HTML and plaintext ([example](title.md)), and will appear on the top of the left panel as shown below:
The example title file here opens up within the user guide documentation itself as another page. Instead, it should appear as code, perhaps pointing to the code file in GitHub. Can you change the link here accordingly?

2024-03-27 21:19 UTC, ckcherry23 commented on docs/ug/customizingReports.md
> +For more information on how to create a Markdown file, see the [Markdown Guide](https://www.markdownguide.org/).
```suggestion
For more information on how to use Markdown, see the [Markdown Guide](https://www.markdownguide.org/).
```

2024-03-27 21:19 UTC, ckcherry23 commented on docs/ug/customizingReports.md
> +The title can render a combination of HTML and plaintext ([example](title.md)), and will appear on the top of the left panel as shown below:
We can indicate that the title uses Markdown syntax explicitly.

```suggestion
The title can render a combination of Markdown/HTML and plaintext ([example](title.md)), and will appear on the top of the left panel as shown below:
```

2024-03-28 20:15 UTC, ckcherry23 commented on docs/ug/customizingReports.md
> +### Add a Title
```suggestion
### Add a title
```

2024-03-28 20:19 UTC, ckcherry23 approved these changes
LGTM!

2024-04-01 07:08 UTC, vvidday approved these changes
LGTM

2024-04-18 16:28 UTC, merged

2024-05-14 11:13 UTC, damithc commented
> Since the preview deployment uses the default build of the RepoSense report, all future builds will use the title component by default.

@sopa301 Does this mean all dashboard will have a default title.md? That shouldn't be the case, as that will force users to override the title.md, turning this opt-in feature into an opt-out feature.

2024-05-14 11:20 UTC, sopa301 commented
Yes prof, I'll create a PR to remove it. If we still want the preview dashboard to have the title, I think we might need to create a separate config for the preview dashboard. 

Another feature that will also stand to gain from this arrangement would be the blurbs.